
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports AspNetCore.ReportingServices.RdlExpressions.ExpressionHostObjectModel
Imports AspNetCore.ReportingServices.ReportProcessing.ReportObjectModel
Imports Microsoft.VisualBasic
Imports System
Imports System.Convert
Imports System.Math
Imports System.Runtime.CompilerServices


Namespace ExpressionHost


    Public Class ReportExprHostImpl
        Inherits ReportExprHost

        Public Sub New(ByVal includeParameters As Boolean, ByVal parametersOnly As Boolean, ByVal reportObjectModel As Object)
            MyBase.New(reportObjectModel)
            Me.m_dataSetHostsRemotable = New RemoteArrayWrapper(Of DataSetExprHost)(New DATA_KontaktAdresse_DataSetExprHost(), New SEL_User_DataSetExprHost(), New LANG_PageFormatString_DataSetExprHost(), New DATA_Report_Translation_DataSetExprHost(), New LANG_Report_Title_DataSetExprHost(), New LANG_DateFormatString_DataSetExprHost(), New SEL_Kontakte_DataSetExprHost(), New SEL_Standort_DataSetExprHost(), New SEL_Gebaeude_DataSetExprHost())
            If (includeParameters = True) Then
                Me.m_reportParameterHostsRemotable = New RemoteArrayWrapper(Of ReportParamExprHost)(New in_report_name_ReportParamExprHost(), New in_stichtag_ReportParamExprHost())
            End If
            If (parametersOnly = True) Then
                Return
            End If
            Me.m_textBoxHostsRemotable = New RemoteArrayWrapper(Of TextBoxExprHost)(New Textbox18_TextBoxExprHost(), New Textbox20_TextBoxExprHost())
        End Sub

        Public Class DATA_KontaktAdresse_DataSetExprHost
            Inherits DataSetExprHost

            Public Sub New()
                MyBase.New
                Me.QueryParametersHost = New QueryParameters_IndexedExprHost()
            End Sub

            Public Class QueryParameters_IndexedExprHost
                Inherits IndexedExprHost

                Default Public Overrides ReadOnly Property Item(ByVal index As Integer) As Object
                    Get

#ExternalSource ("Expr0end", 0)
                        Return Parameters!in_kt_uid.Value

#End ExternalSource
                    End Get
                End Property
            End Class
        End Class

        Public Class SEL_User_DataSetExprHost
            Inherits DataSetExprHost

            Public Sub New()
                MyBase.New
                Me.QueryParametersHost = New QueryParameters_IndexedExprHost()
            End Sub

            Public Class QueryParameters_IndexedExprHost
                Inherits IndexedExprHost

                Default Public Overrides ReadOnly Property Item(ByVal index As Integer) As Object
                    Get

#ExternalSource ("Expr1end", 0)
                        Return Parameters!proc.Value

#End ExternalSource
                    End Get
                End Property
            End Class
        End Class

        Public Class LANG_PageFormatString_DataSetExprHost
            Inherits DataSetExprHost

            Public Sub New()
                MyBase.New
                Me.QueryParametersHost = New QueryParameters_IndexedExprHost()
            End Sub

            Public Class QueryParameters_IndexedExprHost
                Inherits IndexedExprHost

                Default Public Overrides ReadOnly Property Item(ByVal index As Integer) As Object
                    Get
                        If (index <= 1) Then
                            If (index <= 0) Then

#ExternalSource ("Expr2end", 0)
                                Return Parameters!in_mandant.Value

#End ExternalSource
                            Else

#ExternalSource ("Expr3end", 0)
                                Return Parameters!in_sprache.Value

#End ExternalSource
                            End If
                        Else
                            If (index <= 2) Then

#ExternalSource ("Expr4end", 0)
                                Return Parameters!in_stichtag.Value

#End ExternalSource
                            Else

#ExternalSource ("Expr5end", 0)
                                Return Parameters!in_report_name.Value

#End ExternalSource
                            End If
                        End If
                    End Get
                End Property
            End Class
        End Class

        Public Class DATA_Report_Translation_DataSetExprHost
            Inherits DataSetExprHost

            Public Sub New()
                MyBase.New
                Me.QueryParametersHost = New QueryParameters_IndexedExprHost()
            End Sub

            Public Class QueryParameters_IndexedExprHost
                Inherits IndexedExprHost

                Default Public Overrides ReadOnly Property Item(ByVal index As Integer) As Object
                    Get
                        If (index <= 1) Then
                            If (index <= 0) Then

#ExternalSource ("Expr6end", 0)
                                Return Parameters!in_mandant.Value

#End ExternalSource
                            Else

#ExternalSource ("Expr7end", 0)
                                Return Parameters!in_sprache.Value

#End ExternalSource
                            End If
                        Else
                            If (index <= 2) Then

#ExternalSource ("Expr8end", 0)
                                Return Parameters!in_stichtag.Value

#End ExternalSource
                            Else

#ExternalSource ("Expr9end", 0)
                                Return Parameters!in_report_name.Value

#End ExternalSource
                            End If
                        End If
                    End Get
                End Property
            End Class
        End Class

        Public Class LANG_Report_Title_DataSetExprHost
            Inherits DataSetExprHost

            Public Sub New()
                MyBase.New
                Me.QueryParametersHost = New QueryParameters_IndexedExprHost()
            End Sub

            Public Class QueryParameters_IndexedExprHost
                Inherits IndexedExprHost

                Default Public Overrides ReadOnly Property Item(ByVal index As Integer) As Object
                    Get
                        If (index <= 1) Then
                            If (index <= 0) Then

#ExternalSource ("Expr10end", 0)
                                Return Parameters!in_mandant.Value

#End ExternalSource
                            Else

#ExternalSource ("Expr11end", 0)
                                Return Parameters!in_sprache.Value

#End ExternalSource
                            End If
                        Else
                            If (index <= 2) Then

#ExternalSource ("Expr12end", 0)
                                Return Parameters!in_stichtag.Value

#End ExternalSource
                            Else

#ExternalSource ("Expr13end", 0)
                                Return Parameters!in_report_name.Value

#End ExternalSource
                            End If
                        End If
                    End Get
                End Property
            End Class
        End Class

        Public Class LANG_DateFormatString_DataSetExprHost
            Inherits DataSetExprHost

            Public Sub New()
                MyBase.New
                Me.QueryParametersHost = New QueryParameters_IndexedExprHost()
            End Sub

            Public Class QueryParameters_IndexedExprHost
                Inherits IndexedExprHost

                Default Public Overrides ReadOnly Property Item(ByVal index As Integer) As Object
                    Get
                        If (index <= 1) Then
                            If (index <= 0) Then

#ExternalSource ("Expr14end", 0)
                                Return Parameters!in_mandant.Value

#End ExternalSource
                            Else

#ExternalSource ("Expr15end", 0)
                                Return Parameters!in_sprache.Value

#End ExternalSource
                            End If
                        Else
                            If (index <= 2) Then

#ExternalSource ("Expr16end", 0)
                                Return Parameters!in_stichtag.Value

#End ExternalSource
                            Else

#ExternalSource ("Expr17end", 0)
                                Return Parameters!in_report_name.Value

#End ExternalSource
                            End If
                        End If
                    End Get
                End Property
            End Class
        End Class

        Public Class SEL_Kontakte_DataSetExprHost
            Inherits DataSetExprHost

            Public Sub New()
                MyBase.New
                Me.QueryParametersHost = New QueryParameters_IndexedExprHost()
            End Sub

            Public Class QueryParameters_IndexedExprHost
                Inherits IndexedExprHost

                Default Public Overrides ReadOnly Property Item(ByVal index As Integer) As Object
                    Get
                        If (index <= 0) Then

#ExternalSource ("Expr18end", 0)
                            Return Parameters!in_standort.Value

#End ExternalSource
                        Else

#ExternalSource ("Expr19end", 0)
                            Return Parameters!in_gebaeude.Value

#End ExternalSource
                        End If
                    End Get
                End Property
            End Class
        End Class

        Public Class SEL_Standort_DataSetExprHost
            Inherits DataSetExprHost

            Public Sub New()
                MyBase.New
                Me.QueryParametersHost = New QueryParameters_IndexedExprHost()
            End Sub

            Public Class QueryParameters_IndexedExprHost
                Inherits IndexedExprHost

                Default Public Overrides ReadOnly Property Item(ByVal index As Integer) As Object
                    Get
                        If (index <= 1) Then
                            If (index <= 0) Then

#ExternalSource ("Expr20end", 0)
                                Return Parameters!in_mandant.Value

#End ExternalSource
                            Else

#ExternalSource ("Expr21end", 0)
                                Return Parameters!in_sprache.Value

#End ExternalSource
                            End If
                        Else

#ExternalSource ("Expr22end", 0)
                            Return Parameters!in_groups.Value

#End ExternalSource
                        End If
                    End Get
                End Property
            End Class
        End Class

        Public Class SEL_Gebaeude_DataSetExprHost
            Inherits DataSetExprHost

            Public Sub New()
                MyBase.New
                Me.QueryParametersHost = New QueryParameters_IndexedExprHost()
            End Sub

            Public Class QueryParameters_IndexedExprHost
                Inherits IndexedExprHost

                Default Public Overrides ReadOnly Property Item(ByVal index As Integer) As Object
                    Get
                        If (index <= 1) Then
                            If (index <= 0) Then

#ExternalSource ("Expr23end", 0)
                                Return Parameters!in_mandant.Value

#End ExternalSource
                            Else

#ExternalSource ("Expr24end", 0)
                                Return Parameters!in_sprache.Value

#End ExternalSource
                            End If
                        Else
                            If (index <= 2) Then

#ExternalSource ("Expr25end", 0)
                                Return Parameters!in_standort.Value

#End ExternalSource
                            Else

#ExternalSource ("Expr26end", 0)
                                Return Parameters!in_groups.Value

#End ExternalSource
                            End If
                        End If
                    End Get
                End Property
            End Class
        End Class

        Public Class Textbox18_TextBoxExprHost
            Inherits TextBoxExprHost

            Public Sub New()
                MyBase.New
                Me.m_paragraphHostsRemotable = New RemoteArrayWrapper(Of ParagraphExprHost)(New Paragraph00_ParagraphExprHost())
            End Sub

            Public Class Paragraph00_ParagraphExprHost
                Inherits ParagraphExprHost

                Public Sub New()
                    MyBase.New
                    Me.m_textRunHostsRemotable = New RemoteArrayWrapper(Of TextRunExprHost)(New TextRun00_TextRunExprHost())
                End Sub

                Public Class TextRun00_TextRunExprHost
                    Inherits TextRunExprHost

                    Public Overrides ReadOnly Property ValueExpr() As Object
                        Get

#ExternalSource ("Expr27end", 0)
                            Return Parameters!in_absender.Value

#End ExternalSource
                        End Get
                    End Property
                End Class
            End Class
        End Class

        Public Class Textbox20_TextBoxExprHost
            Inherits TextBoxExprHost

            Public Sub New()
                MyBase.New
                Me.m_paragraphHostsRemotable = New RemoteArrayWrapper(Of ParagraphExprHost)(New Paragraph00_ParagraphExprHost())
            End Sub

            Public Class Paragraph00_ParagraphExprHost
                Inherits ParagraphExprHost

                Public Sub New()
                    MyBase.New
                    Me.m_textRunHostsRemotable = New RemoteArrayWrapper(Of TextRunExprHost)(New TextRun00_TextRunExprHost())
                End Sub

                Public Class TextRun00_TextRunExprHost
                    Inherits TextRunExprHost

                    Public Overrides ReadOnly Property ValueExpr() As Object
                        Get

#ExternalSource ("Expr28end", 0)
                            Return "Z�rich, " & System.DateTime.Now.ToString("dd.MM.yyyy")

#End ExternalSource
                        End Get
                    End Property
                End Class
            End Class
        End Class

        Public Class in_report_name_ReportParamExprHost
            Inherits ReportParamExprHost

            Default Public Overrides ReadOnly Property Item(ByVal index As Integer) As Object
                Get

#ExternalSource ("Expr29end", 0)
                    Return Globals!ReportName

#End ExternalSource
                End Get
            End Property
        End Class

        Public Class in_stichtag_ReportParamExprHost
            Inherits ReportParamExprHost

            Default Public Overrides ReadOnly Property Item(ByVal index As Integer) As Object
                Get

#ExternalSource ("Expr30end", 0)
                    Return System.DateTime.Now.ToString("dd.MM.yyyy")

#End ExternalSource
                End Get
            End Property
        End Class


    End Class


End Namespace
